#!/usr/bin/env python3
"""
Denno Career OS — Automated Cryptographic Secrets Generator

Generates high-entropy 256-bit cryptographically secure secrets for:
- JWT_SECRET
- POSTGRES_PASSWORD
- METRICS_SECRET_KEY
- SESSION_SECRET_KEY

Optionally writes or updates a production .env file with generated values.
"""

import sys
import secrets
import argparse
from pathlib import Path


def generate_secrets() -> dict[str, str]:
    return {
        "JWT_SECRET": secrets.token_hex(32),            # 256-bit entropy hex string
        "POSTGRES_PASSWORD": secrets.token_urlsafe(24),   # 192-bit entropy URL-safe string
        "METRICS_SECRET_KEY": secrets.token_hex(24),     # 192-bit entropy hex string
        "SESSION_SECRET_KEY": secrets.token_hex(32),     # 256-bit entropy hex string
    }


def main():
    parser = argparse.ArgumentParser(
        description="Generate cryptographically secure production secrets for Denno Career OS."
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        default=None,
        help="Path to output file (e.g., .env.production). If omitted, prints secrets to stdout."
    )
    parser.add_argument(
        "--quiet", "-q",
        action="store_true",
        help="Do not print explanatory header text."
    )
    args = parser.parse_args()

    sec = generate_secrets()

    if not args.quiet:
        print("==========================================================================")
        print("[SECURITY] DENNO CAREER OS -- PRODUCTION SECRETS GENERATOR")
        print("==========================================================================")
        print("The following high-entropy cryptographic secrets have been freshly generated:")
        print()
        for k, v in sec.items():
            print(f"  {k:<22} = {v}")
        print()
        print("--------------------------------------------------------------------------")

    if args.output:
        out_path = Path(args.output)
        content = [
            "# Generated by scripts/generate_secrets.py",
            f"JWT_SECRET={sec['JWT_SECRET']}",
            f"POSTGRES_PASSWORD={sec['POSTGRES_PASSWORD']}",
            f"METRICS_SECRET_KEY={sec['METRICS_SECRET_KEY']}",
            f"SESSION_SECRET_KEY={sec['SESSION_SECRET_KEY']}",
        ]
        out_path.write_text("\n".join(content) + "\n", encoding="utf-8")
        print(f"✅ Written to {out_path.resolve()}")
    else:
        print("Copy the keys above into your server's .env file before launching!")
        print("==========================================================================")


if __name__ == "__main__":
    main()
